### ISSUE TITLE
Websockets don't work

### ISSUE THREAD

**Issue by epoberezhny** [lionsharecapital/lionshare-api#88]
Hi! I'm trying to connect to your websocket. The connection is established, but no messages.

**Comment by tylerthebuildor** [comment]
If you used the deploy to Heroku button you probably need to go into the environment variables on the Heroku dashboard and add those in as they will always be set to blank for every new deployment. This should fix your problem. I can help you but this isn't the place for that instead hit me up on twitter @tylerbuchea.

Also if you give context and narrow down your problem before opening issues on a repo you will get better responses from people. For instance the issue you're having is probably not related to the code itself but to user error. Try and be absolutely certain this isn't the case next time you open an issue and be able to back up your claim. This makes it easier to take action on an issue. With no context a developer has no idea where to begin.

Not trying to sound snarky just passing on the Github etiquette knowledge I've learned the hard way. Cheers @epoberezhny 🍻
